### ISSUE TITLE
GREAT Extension - Feature request:

### ISSUE THREAD

**Issue by iSchorsch** [tobiasdueser/StockPortfolio-MoneyMoney#1]
Hi, first of all: I love your extension! It's a great help to monitor the stock, my employer gives me.
I do have a feature request: Please advise or implement a feature to add stocks.
I get new stocks on a regular basis but see no way, how to add them. I do have to delete the account and renew it. But doing so will delete the history as well.

THANKS a million!

**Comment by iSchorsch** [comment]
Found a way that solves my issue: right-klick and "Zugangsdaten bearbeiten" then just add the stocks.
-> closed

**Comment by tobiasdueser** [comment]
Just saw this issue. Somehow I didn't get any notifications from Github. I updated the readme to make it more clear. Thanks!

**Comment by iSchorsch** [comment]
Hi Tobias! Great news! Thank you so much for your effort! Is there a PayPal account I can send a small donation to your effort?
